package model;
// Generated Mar 22, 2017 3:59:01 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hibernate.HibernateException;
import util.HibernateUtil;

/**
 * Tables generated by hbm2java
 */
public class Tables  implements java.io.Serializable, Persistence  {

    private int id;
    private String tabName;
    private Date createdAt;
    private Date updatedAt;
    private String createdBy;
    private String updatedBy;
    private Short status;
    
    public static Short STATUS_FREE = 0;
    public static Short STATUS_BUSY = 1;
    public static Map<Short, String> STATUS_DEFINITION; static {
        STATUS_DEFINITION = new HashMap<>();
        STATUS_DEFINITION.put(STATUS_FREE, "Bàn Trống");
        STATUS_DEFINITION.put(STATUS_BUSY, "Có Khách");
    }

    public Tables() {
        this.createdAt = new Date();
        this.updatedAt = new Date();
        this.createdBy = "Lai";
        this.updatedBy = "Lai";
        this.status = STATUS_FREE;
    }

    public Tables(String tabName, Date createdAt, Date updatedAt, String createdBy, String updatedBy, Short status) {
       this.tabName = tabName;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTabName() {
        return this.tabName;
    }
    
    public void setTabName(String tabName) {
        this.tabName = tabName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }

    public static List<Tables> getAll() {
        List<Tables> all = new ArrayList<Tables>();
        all = HibernateUtil.executeSelectHQLQuery("from Tables");
        return all;
    }
    
    public boolean insert() {
        try {
            HibernateUtil.executeInsertHQLQuery(this);
        } catch (HibernateException he) {
            System.out.println("error while run func HibernateUtil.executeInsertHQLQuery to insert Tables record: " + he.getMessage());
            return false;
        }
        return true;

    }
    
    public boolean update() {
        String query = String.format("update Tables set status=%d, tab_name='%s' where id=%d", this.status, this.tabName, this.id);
        try{
            HibernateUtil.executeUpdateHQLQuery(query);
        } catch (HibernateException he){
            return false;
        }
        return true;
    }
    
    public boolean delete() {
        String query = String.format("delete Tables where id=%d", this.id);
        try {
            HibernateUtil.executeUpdateHQLQuery(query);
        } catch (HibernateException he) {
            System.out.println("error while run func HibernateUtil.executeUpdateHQLQuery to delete Tables record: " + he.getMessage());
            return false;
        }
        return true;
    }

}
